### ISSUE TITLE
DNS redirect is not excepted by app as valid route.

### ISSUE THREAD

**Issue by JakeTobin** [hacksu/kenthackenough#15]
<img width="373" alt="screenshot 2015-09-15 16 42 34" src="https://cloud.githubusercontent.com/assets/2688709/9893165/e2f8c18c-5be3-11e5-8e6e-bd0d103e8df8.png">

**Comment by pdilyard** [comment]
Solved by adding server_name www.khe.io to the SSL server in nginx
