### ISSUE TITLE
Updates start with negative time delta

### ISSUE THREAD

**Issue by IAPark** [hacksu/kenthackenough#9]
It seems that when new messages are submitted their created timestamp is set a minute or more in the future.

**Comment by IAPark** [comment]
Actually it's looking like it's getting created a whole lot more than a minute in the future. My app is reading -3 hours.

**Comment by pdilyard** [comment]
Make sure you take time zone into consideration when you parse the date. Mine is reading about 3 minutes in the future

**Comment by IAPark** [comment]
Hum I don't know let me look at it more closely. Maybe I'm printing the wrong variable. I'm comparing milliseconds so I don't think it should matter.

**Comment by pdilyard** [comment]
Milliseconds since 1/1/1970 EST are still different from milliseconds since 1/1/1970 PST

**Comment by IAPark** [comment]
How? I thought those were both since 1/1/1970 GMT

Though I suspect what I'm doing wrong is when I import them assuming they're in my time zone when they'll really in GMT.

**Comment by pdilyard** [comment]
Oh yeah, you're right. I just remember having this exact same issue on Android last time I dealt with a timestamp from a server

**Comment by pdilyard** [comment]
I _think_ the only problem is the 3 minutes. But I'll look at it more closely when I get to this one

**Comment by IAPark** [comment]
Do you know exactly what kind of dating is coming back in the json?

**Comment by IAPark** [comment]
Well fixed it that took long enough. Yet another 3rd party library, but it seems to be working flawlessly. Though still reporting about -1 minute when its first created.

**Comment by pdilyard** [comment]
I'll take a look at the minutes soon. Thanks Isaac!

**Comment by pdilyard** [comment]
Just a problem with the server time :)
